title: 孤雛淚
description: 晚安．月亮─床邊故事：孤雛淚
time: Tue, 26 Mar 2024 03:45:47 +0000
items:
  - title: 00. 孤雛淚
    size: 633364
    duration: 63
  - title: 01. 奧利佛的初生
    size: 5178358
    duration: 541
  - title: 02. 奧利佛的悲願
    size: 3881560
    duration: 388
  - title: 03. 掃煙囪的學徒
    size: 4570165
    duration: 462
  - title: 04. 法官大人
    size: 4658704
    duration: 471
  - title: 05. 棺材店的徒弟
    size: 4882172
    duration: 493
  - title: 06. 奧利佛的反擊
    size: 4328861
    duration: 438
  - title: 07. 再見，迪克！
    size: 5158385
    duration: 532
  - title: 08. 到倫敦去
    size: 5074854
    duration: 521
  - title: 09. 賊窟
    size: 5101221
    duration: 517
  - title: 10. 奇怪的遊戲
    size: 4497057
    duration: 458
  - title: 11. 捉扒手
    size: 4489498
    duration: 451
  - title: 12. 老紳士
    size: 4209064
    duration: 428
  - title: 13. 惡漢畢爾
    size: 4604179
    duration: 460
  - title: 14. 少女南茜
    size: 4820369
    duration: 480
  - title: 15. 溫暖的家
    size: 4015190
    duration: 407
  - title: 16. 考驗
    size: 4626211
    duration: 462
  - title: 17. 一去不返
    size: 4538079
    duration: 460
  - title: 18. 重陷賊窟
    size: 4615588
    duration: 464
  - title: 19. 南茜的反擊
    size: 4436280
    duration: 448
  - title: 20. 善與惡的邊緣
    size: 5374247
    duration: 534
  - title: 21. 邪惡的計畫
    size: 4334665
    duration: 436
  - title: 22. 新鞋子
    size: 5115749
    duration: 520
  - title: 23. 遠行
    size: 5174287
    duration: 521
  - title: 24. 行竊
    size: 4621739
    duration: 476
  - title: 25. 行跡敗露
    size: 4924208
    duration: 503
  - title: 26. 老太婆的秘密
    size: 5553369
    duration: 570
  - title: 27. 悲傷的南茜
    size: 4491726
    duration: 460
  - title: 28. 神秘的男人
    size: 4172729
    duration: 427
  - title: 29. 奧利佛的危機
    size: 4682208
    duration: 480
  - title: 30. 溫暖人間
    size: 5012690
    duration: 521
  - title: 31. 落難的天使
    size: 4615709
    duration: 480
  - title: 32. 警官來查
    size: 4441940
    duration: 457
  - title: 33. 逃過一劫
    size: 4655495
    duration: 475
  - title: 34. 大病初癒
    size: 4745980
    duration: 473
  - title: 35. 尋找老紳士
    size: 4938940
    duration: 503
  - title: 36. 奇異的夢
    size: 4813559
    duration: 490
  - title: 37. 陌生男子
    size: 4291457
    duration: 439
  - title: 38. 邦布爾的心機
    size: 4818642
    duration: 494
  - title: 39. 祕密交易
    size: 3856773
    duration: 398
  - title: 40. 神秘的蒙克司
    size: 4462364
    duration: 453
  - title: 41. 偷聽
    size: 4699516
    duration: 483
  - title: 42. 求見梅麗夫人
    size: 4177921
    duration: 435
  - title: 43. 密告
    size: 3949753
    duration: 418
  - title: 44. 重逢
    size: 5205220
    duration: 531
  - title: 45. 重要會議
    size: 5189553
    duration: 525
  - title: 46. 南茜的處境
    size: 3445863
    duration: 350
  - title: 47. 跟蹤
    size: 5230492
    duration: 524
  - title: 48. 倫敦橋
    size: 3861912
    duration: 395
  - title: 49. 最後的告白
    size: 4068923
    duration: 411
  - title: 50. 南茜之死
    size: 4635622
    duration: 474
  - title: 51. 南茜的陰影
    size: 5479553
    duration: 541
  - title: 52. 亡命之徒
    size: 5098905
    duration: 519
  - title: 53. 真相大白
    size: 4777286
    duration: 499
  - title: 54. 悔過書
    size: 4594410
    duration: 475
  - title: 55. 惡人的下場
    size: 4215884
    duration: 428
  - title: 56. 惡有惡報
    size: 4542041
    duration: 469
  - title: 57. 惡徒的末日
    size: 4654045
    duration: 474
  - title: 58. 秘密文件
    size: 4510420
    duration: 463
  - title: 59. 得知真相
    size: 4149281
    duration: 426
  - title: 60. 不再流淚的孤雛
    size: 4060943
    duration: 413
